site_name: IR Explorer
use_directory_urls: false
nav:
    - Getting started: started.md
    - Demos: demos.md
    - Exploring IR: todo.md
    - Annotating IR: todo.md
    - Comparing IR: todo.md
    - Advanced functionality: todo.md
    - Scripting: todo.md
theme:
  name: 'material'
  font: false
  palette:
    primary: 'indigo'
    accent: 'red'
  logo:
    icon: 'list'
markdown_extensions:
  - admonition
  - attr_list
  